spring:
  application:
    name: dynamic-datasource-sample
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组，默认值为master，这里设置成了mysql
      primary: mysql
      # 严格匹配数据源，默认为false，true未匹配到指定数据源时抛异常，false使用默认数据源
      strict: false
      datasource:
        mysql:
          url: jdbc:mysql://127.0.0.1:3306/nacos?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: 123
          driver-class-name: com.mysql.jdbc.Driver

        clickhouse:
          url: jdbc:clickhouse://127.0.0.1:8123/test
          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
          username: ck
          password: 123456

